package keystroke

import (
	"github.com/gdamore/tcell/v2"
)

var TcellKeyToString = map[tcell.Key]string {
	tcell.KeyEnter:          "<CR>",
	tcell.KeyBackspace:      "<BS>",
	tcell.KeyTab:            "<Tab>",
	tcell.KeyBacktab:        "<Backtab>",
	tcell.KeyEsc:            "<Esc>",
	tcell.KeyBackspace2:     "<Backspace2>",
	tcell.KeyDelete:         "<Del>",
	tcell.KeyInsert:         "<Ins>",
	tcell.KeyUp:             "<Up>",
	tcell.KeyDown:           "<Down>",
	tcell.KeyLeft:           "<Left>",
	tcell.KeyRight:          "<Right>",
	tcell.KeyHome:           "<Home>",
	tcell.KeyEnd:            "<End>",
	tcell.KeyUpLeft:         "<UpLeft>",
	tcell.KeyUpRight:        "<UpRight>",
	tcell.KeyDownLeft:       "<DownLeft>",
	tcell.KeyDownRight:      "<DownRight>",
	tcell.KeyCenter:         "<Center>",
	tcell.KeyPgDn:           "<PageDown>",
	tcell.KeyPgUp:           "<PageUp>",
	tcell.KeyClear:          "<Clear>",
	tcell.KeyExit:           "<Exit>",
	tcell.KeyCancel:         "<Cancel>",
	tcell.KeyPause:          "<Pause>",
	tcell.KeyPrint:          "<Print>",
	tcell.KeyF1:             "<F1>",
	tcell.KeyF2:             "<F2>",
	tcell.KeyF3:             "<F3>",
	tcell.KeyF4:             "<F4>",
	tcell.KeyF5:             "<F5>",
	tcell.KeyF6:             "<F6>",
	tcell.KeyF7:             "<F7>",
	tcell.KeyF8:             "<F8>",
	tcell.KeyF9:             "<F9>",
	tcell.KeyF10:            "<F10>",
	tcell.KeyF11:            "<F11>",
	tcell.KeyF12:            "<F12>",
	tcell.KeyCtrlA:          "<C-A>",
	tcell.KeyCtrlB:          "<C-B>",
	tcell.KeyCtrlC:          "<C-C>",
	tcell.KeyCtrlD:          "<C-D>",
	tcell.KeyCtrlE:          "<C-E>",
	tcell.KeyCtrlF:          "<C-F>",
	tcell.KeyCtrlG:          "<C-G>",
	tcell.KeyCtrlJ:          "<C-J>",
	tcell.KeyCtrlK:          "<C-K>",
	tcell.KeyCtrlL:          "<C-L>",
	tcell.KeyCtrlN:          "<C-N>",
	tcell.KeyCtrlO:          "<C-O>",
	tcell.KeyCtrlP:          "<C-P>",
	tcell.KeyCtrlQ:          "<C-Q>",
	tcell.KeyCtrlR:          "<C-R>",
	tcell.KeyCtrlS:          "<C-S>",
	tcell.KeyCtrlT:          "<C-T>",
	tcell.KeyCtrlU:          "<C-U>",
	tcell.KeyCtrlV:          "<C-V>",
	tcell.KeyCtrlW:          "<C-W>",
	tcell.KeyCtrlX:          "<C-X>",
	tcell.KeyCtrlY:          "<C-Y>",
	tcell.KeyCtrlZ:          "<C-Z>",
	tcell.KeyCtrlSpace:      "<C-Space>",
	tcell.KeyCtrlUnderscore: "<C-_>",
	tcell.KeyCtrlRightSq:    "<C-]>",
	//tcell.KeyCtrlLeftSq:	 "<C-[>",
	tcell.KeyCtrlBackslash:  "<C-\\>",
	tcell.KeyCtrlCarat:      "<C-^>",
}

var SpecialCharacters []string = []string {
	"<Space>",
	"<CR>",
	"<BS>",
	"<Tab>",
	"<Backtab>",
	"<Esc>",
	"<Backspace>",
	"<Del>",
	"<Ins>",
	"<Up>",
	"<Down>",
	"<Left>",
	"<Right>",
	"<Home>",
	"<End>",
	"<UpLeft>",
	"<UpRight>",
	"<DownLeft",
	"<DownRight>",
	"<Center>",
	"<PageDown>",
	"<PageUp>",
	"<Clear>",
	"<Exit>",
	"<Cancel>",
	"<Pause>",
	"<Print>",
	"<F1>",
	"<F2>",
	"<F3>",
	"<F4>",
	"<F5>",
	"<F6>",
	"<F7>",
	"<F8>",
	"<F9>",
	"<F10>",
	"<F11>",
	"<F12>",
	"<C-A>",
	"<C-B>",
}
